apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-allow-gress
  namespace: applications
spec:
  podSelector:
          {}
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
