apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pri-non
  name: pri-yes
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox
    name: pri-yes
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
