apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
  annotations: 
    container.apparmor.security.beta.kubernetes.io/secure: localhost/docker-nginx
    run: secure
  name: secure
spec:
  containers:
  - image: docker.io/nginx
    name: secure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
